set(SDL2_INCLUDE_DIRS "${PROJECT_WORKING_DIRECTORY}/3rdparty/SDL2/include/")
set(SDL2_LIBRARIES
    "${PROJECT_WORKING_DIRECTORY}/3rdparty/SDL2/lib/x64/SDL2.lib;${PROJECT_WORKING_DIRECTORY}/3rdparty/SDL2/lib/x64/SDL2main.lib"
)

string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
